FROM ardupilot/ardupilot-dev-base:v0.2

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    iproute2 \
    iputils-ping \
    net-tools \
    iw \
    wireless-tools \
    batctl \
    ebtables \
    kmod \
    procps \
    tcpdump \
    cmake \
    ninja-build \
    pkg-config \
    python3 \
    python3-pip \
    ca-certificates \
    time \
    neovim \
    linux-tools-common \
    linux-tools-generic \
    && rm -rf /var/lib/apt/lists/*

RUN python3 --version

RUN PERF_PATH="$(find /usr/lib/linux-tools -type f -name perf | head -n 1)" \
    && if [ -n "$PERF_PATH" ]; then \
         ln -sf "$PERF_PATH" /usr/bin/perf; \
       fi

WORKDIR /ardupilot

RUN git clone --recurse-submodules \
    https://github.com/ArduPilot/ardupilot.git .

RUN ./waf configure --board sitl \
    && ./waf copter

ENV PATH="/root/.local/bin:/ardupilot/Tools/autotest:/ardupilot/build/sitl/bin:${PATH}"

CMD ["/bin/bash"]
